{
 "title": "TMS",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Security Based Trust",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_benchmark_node_Security_Score{job=\"kube-security\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Capacity Based Trust",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tms_capacity", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Interaction Based Trust",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tms_interaction{job=\"kube-interaction\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tms_score", "legendFormat": "{{exported_instance}}" }
   ]
  }
 ]
}